<a href="https://colab.research.google.com/github/aslbekrazzoqberdi/Nump-data/blob/main/10_Numpy_Manipulating_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


#### WE MAKE 1D ARRAY TO 2D ARRAY

In [ ]:
new_arr = arr.reshape(3,4)

In [ ]:
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### WE MAKE  1D ARRAY TO 3D ARRAY

In [ ]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
new_arr2 = arr.reshape(2,2,3)
print(new_arr2)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
arr7 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(arr7)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


###  WE MAKE 1D ARRAY TO 4D ARRAY

In [ ]:
new_arr7 = arr7.reshape(4,2,2)


In [ ]:
print(new_arr7)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
