<a href="https://colab.research.google.com/github/aslbekrazzoqberdi/Nump-data/blob/main/12_Numpy_Matrix_Transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


#### LETS TRANSPOSE ARRAY  YANI COLUMN BN ROW O'RNI ALMASHADI

In [ ]:
np.transpose(arr)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
print(arr)

[[1 2 3 4]
 [5 6 7 8]]
