<a href="https://colab.research.google.com/github/aslbekrazzoqberdi/Nump-data/blob/main/15_Numpy_Sort().ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy   as np

In [ ]:
arr = np.array(['apple', 'lemon', 'banana', 'apricot', 'cherry'])

In [ ]:
new_arr = np.sort(arr)
print(new_arr)

['apple' 'apricot' 'banana' 'cherry' 'lemon']


#### LETS MOVE ON  2D ARRAY SORTING

In [ ]:
arr2 = np.array([[10,6,45,12],[25,1,20,89]])
print(arr2)

[[10  6 45 12]
 [25  1 20 89]]


In [ ]:
print(np.sort(arr2))

[[ 6 10 12 45]
 [ 1 20 25 89]]
