<a href="https://colab.research.google.com/github/aslbekrazzoqberdi/Nump-data/blob/main/19_Numpy_Searching_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,7,6,9,3,4,6,7,10,12,7,5,6,])

In [ ]:
x = np.where(arr==7)


print(x)


(array([ 1,  7, 10]),)


### BIZ LISTDAN SEARCHB QILAMZ VA XOXLAGAN ELEMENTNI  KIRITAMZ NATIJADA INDEX KORSATKICHINI KELTIRIB CHIQARADI

 ### LIST ICHIDAN FAQAT JUFT ELEMENTLARNI IZLAYMIZ

In [ ]:
arr

array([ 1,  7,  6,  9,  3,  4,  6,  7, 10, 12,  7,  5,  6])

In [ ]:
x = np.where(arr%2 == 0)
print(x)

(array([ 2,  5,  6,  8,  9, 12]),)


### LIST ICHIDAN FAQAT TOQ SONLARNI IZLAYMZ

In [ ]:
arr

array([ 1,  7,  6,  9,  3,  4,  6,  7, 10, 12,  7,  5,  6])

In [ ]:
x = np.where(arr%2 != 0)
print(x)

(array([ 0,  1,  3,  4,  7, 10, 11]),)
