<a href="https://colab.research.google.com/github/aslbekrazzoqberdi/Nump-data/blob/main/20_Searchsorted_method.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x = np.searchsorted(arr, 9)
print(x)

8


In [ ]:
y = np.searchsorted(arr, 15)
print(y)

9


In [ ]:
z = np.searchsorted(arr, 5, side = 'left' )
print(z)

4


In [ ]:
t = np.searchsorted(arr, [6,7])
print(t)

[5 6]


In [ ]:
arr2 = np.array([1,3,2,1,2,5,32,53,21,67])
print(arr2)

[ 1  3  2  1  2  5 32 53 21 67]


In [ ]:
d = np.sort(arr2)
print(d)

[ 1  1  2  2  3  5 21 32 53 67]


In [ ]:
f = np.searchsorted(d, 2)
print(f)

2
