<a href="https://colab.research.google.com/github/aslbekrazzoqberdi/Nump-data/blob/main/25_Numy_Arange%2C_Linspace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.arange(1,10)

In [ ]:
print(x)

[1 2 3 4 5 6 7 8 9]


In [ ]:
y = np.arange(1,21,2)

In [ ]:
print(y)

[ 1  3  5  7  9 11 13 15 17 19]


#### ARRAYS OF ONES AND ZEROS

In [ ]:
arr1 = np.zeros(5)

In [ ]:
print(arr1)

[0. 0. 0. 0. 0.]


In [ ]:
arr2 = np.ones((3,4))

In [ ]:
print(arr2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
