<a href="https://colab.research.google.com/github/aslbekrazzoqberdi/Nump-data/blob/main/27_28_Random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.random.rand()

In [ ]:
print(x)

0.10940660519392031


In [ ]:
arr = np.array([21,35,89,22,13,65,79])
print(arr)

[21 35 89 22 13 65 79]


In [ ]:
y = np.random.rand(5)
print(y)

[0.24953328 0.62127101 0.30368477 0.86955671 0.6689362 ]


In [ ]:
z = np.random.rand(4,4)
print(z)

[[0.40196382 0.17864455 0.98386526 0.50174088]
 [0.83933557 0.95763212 0.02476884 0.42865635]
 [0.86483438 0.29555048 0.86880325 0.47789121]
 [0.60162786 0.61531708 0.62033741 0.37295968]]
