<a href="https://colab.research.google.com/github/aslbekrazzoqberdi/Nump-data/blob/main/2_Numpy_N_dimension.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x = np.array([1,2,3])
x

array([1, 2, 3])

#### ARR0

In [ ]:
arr0 = np.array(20)
arr0

array(20)

In [ ]:
print(arr0)

20


In [ ]:
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [ ]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
