<a href="https://colab.research.google.com/github/aslbekrazzoqberdi/Nump-data/blob/main/3_Array_Indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,3,4])

In [ ]:
print(arr1)

[1 2 3 4]


In [ ]:
print(arr1[3])

4


In [ ]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr2[0,2])

3


In [ ]:
x = print(arr2[0,-2])


2


In [ ]:
y = print(arr2[-2,2])

3
