<a href="https://colab.research.google.com/github/aslbekrazzoqberdi/Nump-data/blob/main/5_Array_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np



In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr)

[1 2 3 4 5 6 7]


In [ ]:
print(arr[1:5])

[2 3 4 5]


In [ ]:
print(arr[:2])

[1 2]


In [ ]:
print(arr[2:])

[3 4 5 6 7]


In [ ]:
arr2 = [10,12,15,47,56,45,20,30,19,50,59]
print(arr2[0:8:3])

[10, 47, 20]


In [ ]:
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr3[1,1:3])

[5 6]


In [ ]:
print(arr3.dtype)

int64


In [ ]:
arr4 = np.array(['apple', 'papple', 'lemon', 'watermelon'])
print(arr4)

['apple' 'papple' 'lemon' 'watermelon']


In [ ]:
print(arr4.dtype)

<U10


In [ ]:
arr7 = np.array([1,2,3,4,5], dtype='S')
print(arr7)

[b'1' b'2' b'3' b'4' b'5']


In [ ]:
print(arr7.dtype)

|S1
