<a href="https://colab.research.google.com/github/aslbekrazzoqberdi/Nump-data/blob/main/9_Numpy_Array_Reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr0 = np.array(10)

In [ ]:
arr0

array(10)

In [ ]:
print(arr0)

10


In [ ]:
print(arr0.shape)   #### EMPTY TUPLE

()


In [ ]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [ ]:
print(arr1.shape)

(6,)


In [ ]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr2.shape)

(2, 3)


In [ ]:
arr3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9,], [10,22,33]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 22 33]]]


In [ ]:
print(arr3.shape)

(2, 2, 3)
