<a href="https://colab.research.google.com/github/aslbekrazzoqberdi/Nump-data/blob/main/Array%2C_Copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])

x = arr.view()


In [ ]:
print(arr)

[1 2 3 4]


In [ ]:
print(x)

[1 2 3 4]


In [ ]:
arr[2] = 9
print(arr)

[1 2 9 4]


In [ ]:
print(x)

[1 2 9 4]


In [ ]:
y = arr.copy()


In [ ]:
print(y)

[1 2 9 4]


In [ ]:
arr[3] = 16
print(arr)

[ 1  2  9 16]


In [ ]:
print(x)

[ 1  2  9 16]


In [ ]:
print(y)

[1 2 9 4]
